# Generated by Django 3.1.1 on 2020-10-05 17:07

from django.db import migrations
import django_enumfield.db.fields
import polls.models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='type',
            field=django_enumfield.db.fields.EnumField(default=0, enum=polls.models.QuestionType),
        ),
    ]
