# Generated by Django 3.1.1 on 2020-10-06 13:55

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_question_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='site',
            field=models.CharField(default='', max_length=200, validators=[django.core.validators.URLValidator()]),
        ),
    ]
