# Generated by Django 3.1.1 on 2020-10-06 14:15

from django.db import migrations, models
import polls.models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_question_site'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='rating',
            field=models.IntegerField(default=1, validators=[polls.models.validate_positive]),
        ),
    ]
